openapi: 3.0.0
info:
  title: User and Plan Management API
  version: 1.0.0
  description: API for managing users and their saved plans

servers:
  - url: http://localhost:3000/
    description: Local server

paths:
  /api/user:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                email:
                  type: string
                savedPlans:
                  type: array
                  items:
                    $ref: "#/components/schemas/Plan"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Invalid user data received
        "409":
          description: User already exists
        "500":
          description: Server error

  /api/user/{uid}/plans:
    get:
      summary: Get user plans
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User plans retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Plan"
        "400":
          description: Uid is required
        "404":
          description: User not found
        "500":
          description: Server error

    post:
      summary: Add a new plan to user
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPlan:
                  $ref: "#/components/schemas/Plan"
      responses:
        "201":
          description: Plan added to saved plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: Uid and plan are required
        "404":
          description: User not found
        "409":
          description: Plan name already exists
        "500":
          description: Server error

  /api/user/{uid}/plans/{planName}:
    put:
      summary: Update a user's plan
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
        - in: path
          name: planName
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPlan:
                  $ref: "#/components/schemas/Plan"
      responses:
        "200":
          description: Plan updated in saved plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "404":
          description: User not found or Plan not found
        "500":
          description: Server error

    delete:
      summary: Delete a user's plan
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
        - in: path
          name: planName
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Plan removed from saved plans
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: "#/components/schemas/User"
        "404":
          description: User not found
        "500":
          description: Server error

components:
  schemas:
    User:
      type: object
      properties:
        uid:
          type: string
        email:
          type: string
        savedPlans:
          type: array
          items:
            $ref: "#/components/schemas/Plan"

    Plan:
      type: object
      properties:
        name:
          type: string
        content:
          type: string
