name: Deploy

on:
  push:
    branches:
      - main
env: 
    VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
    VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
    VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
    VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
    VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
    VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
    VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install 
        run: |
          cd client
          npm install

      - name: Build 
        run: |
          cd client
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: client/dist
          token: ${{ secrets.GH_TOKEN }}
